### ISSUE TITLE
Tiny Typos #1

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/BG1_Romantic_Encounters#14]
https://github.com/Gibberlings3/BG1_Romantic_Encounters/blob/f1dfd555c14345b4b108fe814fd0a8a3c2aff79f/bg1re/necromancer/scripts/c%23q11nec.baf#L74
https://github.com/Gibberlings3/BG1_Romantic_Encounters/blob/f1dfd555c14345b4b108fe814fd0a8a3c2aff79f/bg1re/necromancer/dialogues/necromancer.d#L928

The res `c#q11be2` does not exist. FWIW, Res `c#q11ne2` exists and could be sensible in those cases

**In the following lines, there are some typos:**
The Res used for the fct `TakePartyItemAll()` should have been `TICxxSCR` instead of `TICxxSCRL`

https://github.com/Gibberlings3/BG1_Romantic_Encounters/blob/f1dfd555c14345b4b108fe814fd0a8a3c2aff79f/bg1re/TICam/dialogues/TICam.d#L725-L731
https://github.com/Gibberlings3/BG1_Romantic_Encounters/blob/f1dfd555c14345b4b108fe814fd0a8a3c2aff79f/bg1re/TICam/dialogues/TICam.d#L754-L760
https://github.com/Gibberlings3/BG1_Romantic_Encounters/blob/f1dfd555c14345b4b108fe814fd0a8a3c2aff79f/bg1re/TICam/dialogues/TICam.d#L795-L801
https://github.com/Gibberlings3/BG1_Romantic_Encounters/blob/f1dfd555c14345b4b108fe814fd0a8a3c2aff79f/bg1re/TICam/dialogues/TICam.d#L824-L830

**Comment by Gitjas** [comment]
Thanks, fixed locally.

**Comment by Gitjas** [comment]
Fixed in v10.
