### ISSUE TITLE
Compatibility issue bg1npc and bg1re

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/BG1_Romantic_Encounters#26]
With bg1 NPC, when Ender Sai leave Tazok Tent, Montaron kill him (https://github.com/Gibberlings3/BG1NPC/blob/3832a3756d8245a3ccccd4a252b690dc5200cf0d/bg1npc/phase2/baf/x%23momur1.baf#L10). However, he reappears as if nothing had happened at the Friendly Arm inn (bg1re).

It could be sensible to add `!Dead(Ender)` to the script: https://github.com/Gibberlings3/BG1_Romantic_Encounters/blob/3deadbb1b0b67bfa868dd1f5a8720a39a6cc7b53/bg1re/endersai/T1EnderAR2301.baf#L6-L10

**Comment by Gitjas** [comment]
I... am surprised it doesn't check that already. Good catch! Thank you!

**Comment by Gitjas** [comment]
Fixed in v12.
